#!/bin/bash
# eduStack welcome page
### BEGIN INIT INFO
# Provides:       welcome
# Required-Start: $network $remote_fs 
# Required-Stop:  $network $remote_fs
# Default-Start:  2 3 4 5 
# Default-Stop:
# Short-Description: eduStack service
# Description:  eduStack service
### END INIT INFO

# Assure that hostname can be resolved
sed -i '/# eduStack-hosts-patch/d' /etc/hosts
echo "127.0.0.1      `hostname`  # eduStack-hosts-patch" >> /etc/hosts

#