#!/bin/bash
# eduStack welcome page
### BEGIN INIT INFO
# Provides:       welcome
# Required-Start: $network $remote_fs 
# Required-Stop:  $network $remote_fs
# Default-Start:  2 3 4 5
# Default-Stop:
# Short-Description: eduStack service
# Description:  eduStack service
### END INIT INFO


ipaddress=`ifconfig | grep inet | awk 'NR==1 {print $2}' | awk 'BEGIN { FS=":" } { print $2 }'`

rm /etc/issue
echo  '' > /etc/issue
cat /etc/issue.ascii >> /etc/issue
echo ""  >> /etc/issue
echo ''  >> /etc/issue
echo "*** Welcome to the eduStack ***"  >> /etc/issue
echo "*** Built using Ubuntu 12.04 - Kernel \r (\l). ***">> /etc/issue


if [ -f "/etc/init.d/networking" ]; then
    if [ "$ipaddress" = "" ] || [ "$ipaddress" = "127.0.0.1" ]; then
        /etc/init.d/networking force-reload
        ipaddress=`ifconfig | grep inet | awk 'NR==1 {print $2}' | awk 'BEGIN { FS=":" } { print $2 }'`
    fi
fi

echo '' >> /etc/issue

if [ "$ipaddress" != "" ] && [ "$ipaddress" != "127.0.0.1" ]; then
  echo "*** You can access the application at http://$ipaddress ***"  >> /etc/issue
	    echo "*** The default username and password is 'iflab' and 'bistu123'. ***"  >> /etc/issue
  echo "*** Please refer to http://edustack.org for details. ***"  >> /etc/issue
  echo "" >> /etc/issue
else
  echo "*** The machine could not configure the network interface.      ***"  >> /etc/issue
  echo "*** Please visit http://edustack.org for details. ***"  >> /etc/issue
  echo "" >> /etc/issue
fi

if [ -f "/home/iflab/firstboot" ]; then
  echo '' >> /etc/issue
  echo "******************************************************************************" >> /etc/issue
  echo "*  To access the console, please use login 'iflab' and password 'iflab'      *" >> /etc/issue
  echo "*                                                                            *" >> /etc/issue
  echo "*                                 WARNING                                    *" >> /etc/issue
  echo "*  For security reasons, upon your first login, you will be prompted to      *" >> /etc/issue 
  echo "*  change the default password.                                              *" >> /etc/issue 
  echo "******************************************************************************" >> /etc/issue
  echo '' >> /etc/issue
fi
