#!/bin/bash
# eduStack welcome page
### BEGIN INIT INFO
# Provides:       welcome
# Required-Start: $network $remote_fs 
# Required-Stop:  $network $remote_fs
# Default-Start:  2 3 4 5 
# Default-Stop:
# Short-Description: eduStack service
# Description:  eduStack service
### END INIT INFO


ipaddress=`ifconfig | grep inet | awk 'NR==1 {print $2}' | awk 'BEGIN { FS=":" } { print $2 }'`

rm /etc/issue
echo  '[0;36m' > /etc/issue
cat /etc/issue.ascii >> /etc/issue
echo "[0m"  >> /etc/issue
echo '[0;36m'  >> /etc/issue
echo "[1m*** Welcome to the eduStack ***"  >> /etc/issue
echo "[1m*** Built using Ubuntu 12.04 - Kernel \r (\l). ***[0m">> /etc/issue


if [ -f "/etc/init.d/networking" ]; then
    if [ "$ipaddress" = "" ] || [ "$ipaddress" = "127.0.0.1" ]; then
        /etc/init.d/networking force-reload
        ipaddress=`ifconfig | grep inet | awk 'NR==1 {print $2}' | awk 'BEGIN { FS=":" } { print $2 }'`
    fi
fi

echo '[1;33m' >> /etc/issue

if [ "$ipaddress" != "" ] && [ "$ipaddress" != "127.0.0.1" ]; then
  echo "[1m*** You can access the application at http://$ipaddress ***"  >> /etc/issue
	    echo "[1m*** The default username and password is 'iflab' and 'bistu123'. ***"  >> /etc/issue
  echo "[1m*** Please refer to http://edustack.org for details. ***[0m"  >> /etc/issue
  echo "" >> /etc/issue
else
  echo "[1m*** The machine could not configure the network interface.      ***"  >> /etc/issue
  echo "[1m*** Please visit http://edustack.org for details. ***[0m"  >> /etc/issue
  echo "" >> /etc/issue
fi

if [ -f "/home/iflab/firstboot" ]; then
  echo '[1;31m' >> /etc/issue
  echo "******************************************************************************" >> /etc/issue
  echo "*  To access the console, please use login 'iflab' and password 'iflab'      *" >> /etc/issue
  echo "*                                                                            *" >> /etc/issue
  echo "*                                 WARNING                                    *" >> /etc/issue
  echo "*  For security reasons, upon your first login, you will be prompted to      *" >> /etc/issue 
  echo "*  change the default password.                                              *" >> /etc/issue 
  echo "******************************************************************************" >> /etc/issue
  echo '[0m' >> /etc/issue
fi
